<p>I think I have traced the error to the destructor of <code>MyWrapperClass</code> which calls a global/static function <code>Destroy</code> (3rd party) on the object passed into the constructor.  Since the object I pass in is a fake, it probably causes <code>Destroy</code> to fail for one reason or another.  So the question is how do I work around this?  In this case, <code>MyWrapperClass</code> is the object under test so I do not want to modify it or mock it out.  I guess I have to find a way to mock the function <code>Destroy</code>.  Will report back if I find out how.</p>